tweaking

diff --git a/ROM/build b/ROM/build
--- a/ROM/build
+++ b/ROM/build
@@ -24,21 +24,22 @@ while [ "$1" != "" ]; do
 done
 
 echo "Assembling z64-${CODE_VERSION}.asm..."
-echo "- creating binary file z64-ROM-${CODE_VERSION}.bin"
+echo "- creating binary file: z64-ROM-${CODE_VERSION}.bin"
+echo "- saving Beebasm output to: output-${CODE_VERSION}.txt"
 beebasm -v -i z64-${CODE_VERSION}.asm > output-${CODE_VERSION}.txt
 
 # Get return code of last command
 result=$?
 
-if [ $WRITE_ROM -eq 1 ]; then
-    if [ $result -eq 0 ]; then
+if [ $result -eq 0 ]; then
+    if [ $WRITE_ROM -eq 1 ]; then    
         echo "Writing to EEPROM..."
-        echo "- using minipro -p AT28C256 -w z64-ROM-${CODE_VERSION}.bin"
+        echo "- minipro -p AT28C256 -w z64-ROM-${CODE_VERSION}.bin"
         minipro -p AT28C256 -w z64-ROM-${CODE_VERSION}.bin
-    else
-	    echo "*** ERROR *** Code failed to assemble. Huh."
-        exit 1
     fi
+else
+    echo "*** ERROR *** Code failed to assemble. Huh."
+    exit 1
 fi
 
 exit 0
